#!/bin/sh
echo
echo "####################################################################"
echo 
echo " _____   _____  _______  _____  _       ____   _    _  _____  "
echo "|  __ \ |  __ \|__   __|/ ____|| |     / __ \ | |  | ||  __ \ "
echo "| |  | || |__) |  | |  | |     | |    | |  | || |  | || |  | |"
echo "| |  | ||  ___/   | |  | |     | |    | |  | || |  | || |  | |"
echo "| |__| || |       | |  | |____ | |____| |__| || |__| || |__| |"
echo "|_____/ |_|       |_|   \_____||______|\____/  \____/ |_____/ "
echo ""
echo "Cam on ban da su dung dich vu cua DptCloud (https://dptcloud.vn)"
echo "DptCloud cung cap dich vu VPS, Cloud Server chat luong cao"
echo "Moi chi tiet vui long lien he:"
echo 
echo "  - Website: https://dptcloud.vn"
echo "  - Discord: https://dsc.gg/dptcloud"
echo "  - Facebook: https://www.facebook.com/dptcloud"
echo "  - Zalo: 0378 548 788"
echo
echo "####################################################################"
